### ISSUE TITLE
can't run

### ISSUE THREAD

**Issue by levantu019** [mbasa/graphhopper-reader-postgis#3]
# Here is my config file
  datareader.file: ""
  graph.location: graph-cache
  db.host: localhost
  db.port: 5432
  db.database: doan
  db.table: graphhopper
  db.schema: public
  db.user: postgres
  db.passwd: admin
  db.tags_to_copy:
 # However, it's error
java.lang.IllegalStateException: Couldn't load from existing folder: graph-cache but also cannot use file for DataReader as it wasn't specified!
	at com.graphhopper.GraphHopper.importOSM(GraphHopper.java:676)
	at com.graphhopper.GraphHopper.process(GraphHopper.java:651)
	at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:615)
	at com.graphhopper.http.GraphHopperManaged.start(GraphHopperManaged.java:103)
	at io.dropwizard.lifecycle.JettyManaged.doStart(JettyManaged.java:27)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:423)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.Server.doStart(Server.java:387)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:53)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:60)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:94)
	at com.graphhopper.application.GraphHopperApplication.main(GraphHopperApplication.java:38)

Help me!!!

**Comment by mbasa** [comment]
Hello. 

Can you try the following : 

* Download the `jar file` from here:  

https://github.com/mbasa/graphhopper/releases/tag/PostGIS-5.3

* delete your graph-cache
```
rm -rf graph-cache
```

* run graphhopper 

```
java  -jar graphhopper-web-5.3.jar server config.yml
```

hopefully, you will be getting messages like this:

```
2022-08-28 22:26:28.543 [main] INFO  c.g.reader.postgis.PostgisReader - Opening DB connection to postgis localhost:5432 to database pgr schema public
```

**Comment by levantu019** [comment]
Thank you, it's very helpful for me. 
However, the traffic data in my postgreSQL database is simplified when graphhopper show it in map. Do you have any solution for this problem?

**Comment by mbasa** [comment]
I just did the following to test: 

1. download an OSM PBF file.
2. used that PBF file with GraphHopper using the `-Ddw.graphhopper.datareader.file=` parameter.
3. created sample routes.
4. converted the PBF into PostGIS using OSM2PO.
5. created a `VIEW` from the PBF table.
```SQL
View definition:
 SELECT philippines_2po_4pgr.id AS osm_id,
    philippines_2po_4pgr.osm_name AS name,
    philippines_2po_4pgr.kmh AS maxspeed,
    philippines_2po_4pgr.oneway,
    philippines_2po_4pgr.fclass,
    philippines_2po_4pgr.geom_way AS geom
   FROM philippines_2po_4pgr;
```
6. used the reader-postgis with the created VIEW in GraphHopper.
7. created sample routes.

Both created sample routes were identical.

**Comment by mbasa** [comment]
Not quite sure why your data is being simplified. Do ensure though that the `fclass` attributes that you will be passing into GraphHopper is identical to the OSM standards.

**Comment by levantu019** [comment]
Yes I will try again, thank you very much

**Comment by levantu019** [comment]
Hi, how to extract oneway, maxspeed,... from other_tags field
